### ISSUE TITLE
Scenario Levers

### ISSUE THREAD

**Issue by drew-sys** [missionpossiblepartnership/mpp-steel-model#27]
**Description**
Create scenario levers at key points in the modelling logic. These levers can be preset in a configuration file that runs when the scenario runs.

**Tasks**
- [x] Create a config file that stores scenarios
Create parameter values for the following model blocks of functionality:
- [x] CAPEX percentage
- [x] WACC
- [x] Energy price % lever
- [x] Commodity price % lever
- [x] Carbon Tax lever
- [x] Resource constraint % lever
- [x] Demand % lever
