### ISSUE TITLE
Implement Logging functionality across the application

### ISSUE THREAD

**Issue by drew-sys** [missionpossiblepartnership/mpp-steel-model#28]
**Description**
Ensure key model output is logged and printed and messages are passed to the appropriate place
- Important model information printed to standard output at runtime
- All model run information sent to a log file
- Include broad range of logging codewords

**Tasks**
- [x] Install logging script
- [x] Ensure logger works across project files
- [x] Create logging output file (separate by model run)
